[project]
name = "ssh_server_monitor_crew"
version = "0.1.0"
description = "A crewAI project to monitor server stats via SSH."
authors = [
    { name = "Your Name", email = "you@example.com" },
]
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai>=0.30.0",
    "crewai-tools>=0.1.0",
    "paramiko>=3.0.0",
]

[project.scripts]

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"
